---
# MegaLinter GitHub Action configuration file for demo
# More info at https://megalinter.io
name: MegaLinter
on:
  workflow_call:
    secrets:
      TEST_SECRET:
        required: false
        type: string
        default: "test-secret"
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To copy our entire code in this ubuntu-latest VM 
      - name: Checkout Code
        uses: actions/checkout@v3
      # To clone our external rule in this ubuntu-latest VM
      - name: cloning-config
        run: |
            git clone https://${{secrets.TEST_SECRET}}@github.com/tcjoel/megalinter-config.git
            mv megalinter-config/rules/.editorconfig .
            mv megalinter-config/mega/.mega-linter.yml .
            ls -al

      # To do the linting of our code with MegaLinter
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v6